services:
  api:
    build:
      context: ./services/api
      dockerfile: Dockerfile
    environment:
      QDRANT_URL: "http://qdrant:6333"
    ports:
      - "8000:8000"
    depends_on:
      - qdrant
    restart: unless-stopped

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage
    restart: unless-stopped

volumes:
  qdrant_storage: {}
